USE [master]
GO
/****** Object:  Database [COSTADB]    Script Date: 17/01/2023 21:16:14 ******/
CREATE DATABASE [COSTADB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COSTADB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\COSTADB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'COSTADB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\COSTADB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [COSTADB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COSTADB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [COSTADB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [COSTADB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [COSTADB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [COSTADB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [COSTADB] SET ARITHABORT OFF 
GO
ALTER DATABASE [COSTADB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [COSTADB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [COSTADB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [COSTADB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [COSTADB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [COSTADB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [COSTADB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [COSTADB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [COSTADB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [COSTADB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [COSTADB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [COSTADB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [COSTADB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [COSTADB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [COSTADB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [COSTADB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [COSTADB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [COSTADB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [COSTADB] SET  MULTI_USER 
GO
ALTER DATABASE [COSTADB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [COSTADB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [COSTADB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [COSTADB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [COSTADB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [COSTADB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [COSTADB] SET QUERY_STORE = OFF
GO
USE [COSTADB]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 17/01/2023 21:16:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](150) NOT NULL,
	[CPF] [bigint] NULL,
	[DATANASCIMENTO] [date] NOT NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [COSTADB] SET  READ_WRITE 
GO
